#ifndef CLIONSTM32TEST_CONFIGURATION_DEFAULT_H
#define CLIONSTM32TEST_CONFIGURATION_DEFAULT_H


#define CONSOLE_GREETING "PC chill core v1.3\r\n"

// TIM1 PWM channels
#define PWM_FRONT TIM1->CCR1   // CH1
#define PWM_BOTTOM TIM1->CCR2  // CH2
#define PWM_BACK TIM1->CCR3    // CH3
#define PWM_TOP TIM1->CCR4     // CH3

#endif //CLIONSTM32TEST_CONFIGURATION_DEFAULT_H
